name:                earth-on-gcs-browser
version:             0.1.0.0
github:              "jisantuc/earth-on-gcs-browser"
license:             BSD3
author:              "James Santucci"
maintainer:          "james.santucci@gmail.com"
copyright:           "2018 James Santucci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jisantuc/earth-on-gcs/earth-on-gcs-browser#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.2.4 && < 1.3
- bytestring >= 0.10.8 && < 0.11
- lens >= 4.16.1 && < 4.17
- random >= 1.1 && < 1.2
- text >= 1.2.3 && < 1.2.4
- wreq >= 0.5.2 && < 0.6

library:
  source-dirs: src
  default-extensions:
    - DeriveGeneric
    - OverloadedStrings

tests:
  earth-on-gcs-browser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - earth-on-gcs-browser
